name: driver_mobile
description: Application mobile chauffeur pour la flotte de vehicules.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.1.0
  geolocator: ^10.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  firebase_messaging: ^15.2.10
  connectivity_plus: ^6.0.3
  flutter_compass: ^0.8.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
