// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZXQlz8tLydBMeFAg-zgnqrNzaVONM6x0',
    appId: '1:119982444575:web:71bd697c56acf1bcd7852a',
    messagingSenderId: '119982444575',
    projectId: 'geoconsulting-fleet',
    authDomain: 'geoconsulting-fleet.firebaseapp.com',
    storageBucket: 'geoconsulting-fleet.firebasestorage.app',
    measurementId: 'G-46BXF9BYSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-zS3GmIhyWupJCaKP4kp0uH4sZfwRmc4',
    appId: '1:119982444575:android:e17916d1dd319a39d7852a',
    messagingSenderId: '119982444575',
    projectId: 'geoconsulting-fleet',
    storageBucket: 'geoconsulting-fleet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0kl40d4Sr51kUf6mOq1HMUTRNt4nsmU',
    appId: '1:119982444575:ios:ab53cc4171c0e80bd7852a',
    messagingSenderId: '119982444575',
    projectId: 'geoconsulting-fleet',
    storageBucket: 'geoconsulting-fleet.firebasestorage.app',
    iosBundleId: 'com.novatech.driverMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID.firebaseio.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.novatech.driverMobile',
  );
}